{
 "title": "Basic observability dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Successful Transactions (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(successful_transactions_total[1m])) / sum(rate(successful_transactions_total[1m]) + rate(failed_transactions_total[1m])) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Transactions (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(failed_transactions_total[1m])) / sum(rate(successful_transactions_total[1m]) + rate(failed_transactions_total[1m])) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency (Last Minute) [s]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(transaction_latency_seconds_sum[1m]) \r\n/ \r\nrate(transaction_latency_seconds_count[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 Latency [s]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(transaction_latency_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transactions Processed [last 5m]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(successful_transactions_total[5m]) + increase(failed_transactions_total[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "successful_transactions_total + failed_transactions_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}